spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/cah
    username: root
    password: 1qayxsw2

  flyway:
    locations: classpath:db/mysql/migration

---

spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    locations: classpath:db/mysql/migration
