spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cah?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: 1qayxsw2

  flyway:
    locations: classpath:db/mysql/migration

---

spring:
  profiles: container
  datasource:
    url: jdbc:${DBMS:postgresql}://${DATABASE_HOST}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    locations: classpath:db/mysql/migration